// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package org.tio.examples.im.common.packets;

/**
 * <pre>
 **
 * 地址
 * </pre>
 *
 * Protobuf type {@code Address}
 */
public  final class Address extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Address)
    AddressOrBuilder {
  // Use Address.newBuilder() to construct.
  private Address(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Address() {
    formattedaddress_ = "";
    adcode_ = "";
    province_ = "";
    city_ = "";
    citycode_ = "";
    district_ = "";
    township_ = "";
    street_ = "";
    streetnumber_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Address(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            formattedaddress_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            adcode_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            province_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            city_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            citycode_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            district_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            township_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            street_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            streetnumber_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.tio.examples.im.common.packets.Chat.internal_static_Address_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.tio.examples.im.common.packets.Chat.internal_static_Address_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.tio.examples.im.common.packets.Address.class, org.tio.examples.im.common.packets.Address.Builder.class);
  }

  public static final int FORMATTEDADDRESS_FIELD_NUMBER = 1;
  private volatile java.lang.Object formattedaddress_;
  /**
   * <pre>
   *地址: 浙江省杭州市西湖区古荡街道天目山路307号钱江·西溪新座
   * </pre>
   *
   * <code>string formattedaddress = 1;</code>
   */
  public java.lang.String getFormattedaddress() {
    java.lang.Object ref = formattedaddress_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      formattedaddress_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *地址: 浙江省杭州市西湖区古荡街道天目山路307号钱江·西溪新座
   * </pre>
   *
   * <code>string formattedaddress = 1;</code>
   */
  public com.google.protobuf.ByteString
      getFormattedaddressBytes() {
    java.lang.Object ref = formattedaddress_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      formattedaddress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADCODE_FIELD_NUMBER = 2;
  private volatile java.lang.Object adcode_;
  /**
   * <pre>
   *330106
   * </pre>
   *
   * <code>string adcode = 2;</code>
   */
  public java.lang.String getAdcode() {
    java.lang.Object ref = adcode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      adcode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *330106
   * </pre>
   *
   * <code>string adcode = 2;</code>
   */
  public com.google.protobuf.ByteString
      getAdcodeBytes() {
    java.lang.Object ref = adcode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      adcode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROVINCE_FIELD_NUMBER = 3;
  private volatile java.lang.Object province_;
  /**
   * <pre>
   *浙江省
   * </pre>
   *
   * <code>string province = 3;</code>
   */
  public java.lang.String getProvince() {
    java.lang.Object ref = province_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      province_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *浙江省
   * </pre>
   *
   * <code>string province = 3;</code>
   */
  public com.google.protobuf.ByteString
      getProvinceBytes() {
    java.lang.Object ref = province_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      province_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CITY_FIELD_NUMBER = 4;
  private volatile java.lang.Object city_;
  /**
   * <pre>
   *杭州
   * </pre>
   *
   * <code>string city = 4;</code>
   */
  public java.lang.String getCity() {
    java.lang.Object ref = city_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      city_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *杭州
   * </pre>
   *
   * <code>string city = 4;</code>
   */
  public com.google.protobuf.ByteString
      getCityBytes() {
    java.lang.Object ref = city_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      city_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CITYCODE_FIELD_NUMBER = 5;
  private volatile java.lang.Object citycode_;
  /**
   * <pre>
   *0571
   * </pre>
   *
   * <code>string citycode = 5;</code>
   */
  public java.lang.String getCitycode() {
    java.lang.Object ref = citycode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      citycode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *0571
   * </pre>
   *
   * <code>string citycode = 5;</code>
   */
  public com.google.protobuf.ByteString
      getCitycodeBytes() {
    java.lang.Object ref = citycode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      citycode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISTRICT_FIELD_NUMBER = 6;
  private volatile java.lang.Object district_;
  /**
   * <pre>
   *西湖区
   * </pre>
   *
   * <code>string district = 6;</code>
   */
  public java.lang.String getDistrict() {
    java.lang.Object ref = district_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      district_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *西湖区
   * </pre>
   *
   * <code>string district = 6;</code>
   */
  public com.google.protobuf.ByteString
      getDistrictBytes() {
    java.lang.Object ref = district_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      district_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOWNSHIP_FIELD_NUMBER = 7;
  private volatile java.lang.Object township_;
  /**
   * <pre>
   *古荡街区
   * </pre>
   *
   * <code>string township = 7;</code>
   */
  public java.lang.String getTownship() {
    java.lang.Object ref = township_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      township_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *古荡街区
   * </pre>
   *
   * <code>string township = 7;</code>
   */
  public com.google.protobuf.ByteString
      getTownshipBytes() {
    java.lang.Object ref = township_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      township_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STREET_FIELD_NUMBER = 8;
  private volatile java.lang.Object street_;
  /**
   * <pre>
   *天目山路
   * </pre>
   *
   * <code>string street = 8;</code>
   */
  public java.lang.String getStreet() {
    java.lang.Object ref = street_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      street_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *天目山路
   * </pre>
   *
   * <code>string street = 8;</code>
   */
  public com.google.protobuf.ByteString
      getStreetBytes() {
    java.lang.Object ref = street_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      street_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STREETNUMBER_FIELD_NUMBER = 9;
  private volatile java.lang.Object streetnumber_;
  /**
   * <pre>
   *307号
   * </pre>
   *
   * <code>string streetnumber = 9;</code>
   */
  public java.lang.String getStreetnumber() {
    java.lang.Object ref = streetnumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      streetnumber_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *307号
   * </pre>
   *
   * <code>string streetnumber = 9;</code>
   */
  public com.google.protobuf.ByteString
      getStreetnumberBytes() {
    java.lang.Object ref = streetnumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      streetnumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getFormattedaddressBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, formattedaddress_);
    }
    if (!getAdcodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, adcode_);
    }
    if (!getProvinceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, province_);
    }
    if (!getCityBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, city_);
    }
    if (!getCitycodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, citycode_);
    }
    if (!getDistrictBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, district_);
    }
    if (!getTownshipBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, township_);
    }
    if (!getStreetBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, street_);
    }
    if (!getStreetnumberBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, streetnumber_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getFormattedaddressBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, formattedaddress_);
    }
    if (!getAdcodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, adcode_);
    }
    if (!getProvinceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, province_);
    }
    if (!getCityBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, city_);
    }
    if (!getCitycodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, citycode_);
    }
    if (!getDistrictBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, district_);
    }
    if (!getTownshipBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, township_);
    }
    if (!getStreetBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, street_);
    }
    if (!getStreetnumberBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, streetnumber_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.tio.examples.im.common.packets.Address)) {
      return super.equals(obj);
    }
    org.tio.examples.im.common.packets.Address other = (org.tio.examples.im.common.packets.Address) obj;

    boolean result = true;
    result = result && getFormattedaddress()
        .equals(other.getFormattedaddress());
    result = result && getAdcode()
        .equals(other.getAdcode());
    result = result && getProvince()
        .equals(other.getProvince());
    result = result && getCity()
        .equals(other.getCity());
    result = result && getCitycode()
        .equals(other.getCitycode());
    result = result && getDistrict()
        .equals(other.getDistrict());
    result = result && getTownship()
        .equals(other.getTownship());
    result = result && getStreet()
        .equals(other.getStreet());
    result = result && getStreetnumber()
        .equals(other.getStreetnumber());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FORMATTEDADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getFormattedaddress().hashCode();
    hash = (37 * hash) + ADCODE_FIELD_NUMBER;
    hash = (53 * hash) + getAdcode().hashCode();
    hash = (37 * hash) + PROVINCE_FIELD_NUMBER;
    hash = (53 * hash) + getProvince().hashCode();
    hash = (37 * hash) + CITY_FIELD_NUMBER;
    hash = (53 * hash) + getCity().hashCode();
    hash = (37 * hash) + CITYCODE_FIELD_NUMBER;
    hash = (53 * hash) + getCitycode().hashCode();
    hash = (37 * hash) + DISTRICT_FIELD_NUMBER;
    hash = (53 * hash) + getDistrict().hashCode();
    hash = (37 * hash) + TOWNSHIP_FIELD_NUMBER;
    hash = (53 * hash) + getTownship().hashCode();
    hash = (37 * hash) + STREET_FIELD_NUMBER;
    hash = (53 * hash) + getStreet().hashCode();
    hash = (37 * hash) + STREETNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getStreetnumber().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.tio.examples.im.common.packets.Address parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tio.examples.im.common.packets.Address parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tio.examples.im.common.packets.Address parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tio.examples.im.common.packets.Address parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tio.examples.im.common.packets.Address parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.tio.examples.im.common.packets.Address parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.tio.examples.im.common.packets.Address parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.tio.examples.im.common.packets.Address parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.tio.examples.im.common.packets.Address parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.tio.examples.im.common.packets.Address parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.tio.examples.im.common.packets.Address prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * 地址
   * </pre>
   *
   * Protobuf type {@code Address}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Address)
      org.tio.examples.im.common.packets.AddressOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tio.examples.im.common.packets.Chat.internal_static_Address_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tio.examples.im.common.packets.Chat.internal_static_Address_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tio.examples.im.common.packets.Address.class, org.tio.examples.im.common.packets.Address.Builder.class);
    }

    // Construct using org.tio.examples.im.common.packets.Address.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      formattedaddress_ = "";

      adcode_ = "";

      province_ = "";

      city_ = "";

      citycode_ = "";

      district_ = "";

      township_ = "";

      street_ = "";

      streetnumber_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.tio.examples.im.common.packets.Chat.internal_static_Address_descriptor;
    }

    public org.tio.examples.im.common.packets.Address getDefaultInstanceForType() {
      return org.tio.examples.im.common.packets.Address.getDefaultInstance();
    }

    public org.tio.examples.im.common.packets.Address build() {
      org.tio.examples.im.common.packets.Address result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.tio.examples.im.common.packets.Address buildPartial() {
      org.tio.examples.im.common.packets.Address result = new org.tio.examples.im.common.packets.Address(this);
      result.formattedaddress_ = formattedaddress_;
      result.adcode_ = adcode_;
      result.province_ = province_;
      result.city_ = city_;
      result.citycode_ = citycode_;
      result.district_ = district_;
      result.township_ = township_;
      result.street_ = street_;
      result.streetnumber_ = streetnumber_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.tio.examples.im.common.packets.Address) {
        return mergeFrom((org.tio.examples.im.common.packets.Address)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.tio.examples.im.common.packets.Address other) {
      if (other == org.tio.examples.im.common.packets.Address.getDefaultInstance()) return this;
      if (!other.getFormattedaddress().isEmpty()) {
        formattedaddress_ = other.formattedaddress_;
        onChanged();
      }
      if (!other.getAdcode().isEmpty()) {
        adcode_ = other.adcode_;
        onChanged();
      }
      if (!other.getProvince().isEmpty()) {
        province_ = other.province_;
        onChanged();
      }
      if (!other.getCity().isEmpty()) {
        city_ = other.city_;
        onChanged();
      }
      if (!other.getCitycode().isEmpty()) {
        citycode_ = other.citycode_;
        onChanged();
      }
      if (!other.getDistrict().isEmpty()) {
        district_ = other.district_;
        onChanged();
      }
      if (!other.getTownship().isEmpty()) {
        township_ = other.township_;
        onChanged();
      }
      if (!other.getStreet().isEmpty()) {
        street_ = other.street_;
        onChanged();
      }
      if (!other.getStreetnumber().isEmpty()) {
        streetnumber_ = other.streetnumber_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.tio.examples.im.common.packets.Address parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.tio.examples.im.common.packets.Address) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object formattedaddress_ = "";
    /**
     * <pre>
     *地址: 浙江省杭州市西湖区古荡街道天目山路307号钱江·西溪新座
     * </pre>
     *
     * <code>string formattedaddress = 1;</code>
     */
    public java.lang.String getFormattedaddress() {
      java.lang.Object ref = formattedaddress_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        formattedaddress_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *地址: 浙江省杭州市西湖区古荡街道天目山路307号钱江·西溪新座
     * </pre>
     *
     * <code>string formattedaddress = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFormattedaddressBytes() {
      java.lang.Object ref = formattedaddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        formattedaddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *地址: 浙江省杭州市西湖区古荡街道天目山路307号钱江·西溪新座
     * </pre>
     *
     * <code>string formattedaddress = 1;</code>
     */
    public Builder setFormattedaddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      formattedaddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *地址: 浙江省杭州市西湖区古荡街道天目山路307号钱江·西溪新座
     * </pre>
     *
     * <code>string formattedaddress = 1;</code>
     */
    public Builder clearFormattedaddress() {
      
      formattedaddress_ = getDefaultInstance().getFormattedaddress();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *地址: 浙江省杭州市西湖区古荡街道天目山路307号钱江·西溪新座
     * </pre>
     *
     * <code>string formattedaddress = 1;</code>
     */
    public Builder setFormattedaddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      formattedaddress_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object adcode_ = "";
    /**
     * <pre>
     *330106
     * </pre>
     *
     * <code>string adcode = 2;</code>
     */
    public java.lang.String getAdcode() {
      java.lang.Object ref = adcode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        adcode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *330106
     * </pre>
     *
     * <code>string adcode = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAdcodeBytes() {
      java.lang.Object ref = adcode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        adcode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *330106
     * </pre>
     *
     * <code>string adcode = 2;</code>
     */
    public Builder setAdcode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      adcode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *330106
     * </pre>
     *
     * <code>string adcode = 2;</code>
     */
    public Builder clearAdcode() {
      
      adcode_ = getDefaultInstance().getAdcode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *330106
     * </pre>
     *
     * <code>string adcode = 2;</code>
     */
    public Builder setAdcodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      adcode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object province_ = "";
    /**
     * <pre>
     *浙江省
     * </pre>
     *
     * <code>string province = 3;</code>
     */
    public java.lang.String getProvince() {
      java.lang.Object ref = province_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        province_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *浙江省
     * </pre>
     *
     * <code>string province = 3;</code>
     */
    public com.google.protobuf.ByteString
        getProvinceBytes() {
      java.lang.Object ref = province_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        province_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *浙江省
     * </pre>
     *
     * <code>string province = 3;</code>
     */
    public Builder setProvince(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      province_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *浙江省
     * </pre>
     *
     * <code>string province = 3;</code>
     */
    public Builder clearProvince() {
      
      province_ = getDefaultInstance().getProvince();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *浙江省
     * </pre>
     *
     * <code>string province = 3;</code>
     */
    public Builder setProvinceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      province_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object city_ = "";
    /**
     * <pre>
     *杭州
     * </pre>
     *
     * <code>string city = 4;</code>
     */
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        city_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *杭州
     * </pre>
     *
     * <code>string city = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *杭州
     * </pre>
     *
     * <code>string city = 4;</code>
     */
    public Builder setCity(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      city_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *杭州
     * </pre>
     *
     * <code>string city = 4;</code>
     */
    public Builder clearCity() {
      
      city_ = getDefaultInstance().getCity();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *杭州
     * </pre>
     *
     * <code>string city = 4;</code>
     */
    public Builder setCityBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      city_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object citycode_ = "";
    /**
     * <pre>
     *0571
     * </pre>
     *
     * <code>string citycode = 5;</code>
     */
    public java.lang.String getCitycode() {
      java.lang.Object ref = citycode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        citycode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *0571
     * </pre>
     *
     * <code>string citycode = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCitycodeBytes() {
      java.lang.Object ref = citycode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        citycode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *0571
     * </pre>
     *
     * <code>string citycode = 5;</code>
     */
    public Builder setCitycode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      citycode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *0571
     * </pre>
     *
     * <code>string citycode = 5;</code>
     */
    public Builder clearCitycode() {
      
      citycode_ = getDefaultInstance().getCitycode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *0571
     * </pre>
     *
     * <code>string citycode = 5;</code>
     */
    public Builder setCitycodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      citycode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object district_ = "";
    /**
     * <pre>
     *西湖区
     * </pre>
     *
     * <code>string district = 6;</code>
     */
    public java.lang.String getDistrict() {
      java.lang.Object ref = district_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        district_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *西湖区
     * </pre>
     *
     * <code>string district = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDistrictBytes() {
      java.lang.Object ref = district_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        district_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *西湖区
     * </pre>
     *
     * <code>string district = 6;</code>
     */
    public Builder setDistrict(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      district_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *西湖区
     * </pre>
     *
     * <code>string district = 6;</code>
     */
    public Builder clearDistrict() {
      
      district_ = getDefaultInstance().getDistrict();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *西湖区
     * </pre>
     *
     * <code>string district = 6;</code>
     */
    public Builder setDistrictBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      district_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object township_ = "";
    /**
     * <pre>
     *古荡街区
     * </pre>
     *
     * <code>string township = 7;</code>
     */
    public java.lang.String getTownship() {
      java.lang.Object ref = township_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        township_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *古荡街区
     * </pre>
     *
     * <code>string township = 7;</code>
     */
    public com.google.protobuf.ByteString
        getTownshipBytes() {
      java.lang.Object ref = township_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        township_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *古荡街区
     * </pre>
     *
     * <code>string township = 7;</code>
     */
    public Builder setTownship(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      township_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *古荡街区
     * </pre>
     *
     * <code>string township = 7;</code>
     */
    public Builder clearTownship() {
      
      township_ = getDefaultInstance().getTownship();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *古荡街区
     * </pre>
     *
     * <code>string township = 7;</code>
     */
    public Builder setTownshipBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      township_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object street_ = "";
    /**
     * <pre>
     *天目山路
     * </pre>
     *
     * <code>string street = 8;</code>
     */
    public java.lang.String getStreet() {
      java.lang.Object ref = street_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        street_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *天目山路
     * </pre>
     *
     * <code>string street = 8;</code>
     */
    public com.google.protobuf.ByteString
        getStreetBytes() {
      java.lang.Object ref = street_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        street_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *天目山路
     * </pre>
     *
     * <code>string street = 8;</code>
     */
    public Builder setStreet(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      street_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *天目山路
     * </pre>
     *
     * <code>string street = 8;</code>
     */
    public Builder clearStreet() {
      
      street_ = getDefaultInstance().getStreet();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *天目山路
     * </pre>
     *
     * <code>string street = 8;</code>
     */
    public Builder setStreetBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      street_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object streetnumber_ = "";
    /**
     * <pre>
     *307号
     * </pre>
     *
     * <code>string streetnumber = 9;</code>
     */
    public java.lang.String getStreetnumber() {
      java.lang.Object ref = streetnumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        streetnumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *307号
     * </pre>
     *
     * <code>string streetnumber = 9;</code>
     */
    public com.google.protobuf.ByteString
        getStreetnumberBytes() {
      java.lang.Object ref = streetnumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        streetnumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *307号
     * </pre>
     *
     * <code>string streetnumber = 9;</code>
     */
    public Builder setStreetnumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      streetnumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *307号
     * </pre>
     *
     * <code>string streetnumber = 9;</code>
     */
    public Builder clearStreetnumber() {
      
      streetnumber_ = getDefaultInstance().getStreetnumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *307号
     * </pre>
     *
     * <code>string streetnumber = 9;</code>
     */
    public Builder setStreetnumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      streetnumber_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:Address)
  }

  // @@protoc_insertion_point(class_scope:Address)
  private static final org.tio.examples.im.common.packets.Address DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.tio.examples.im.common.packets.Address();
  }

  public static org.tio.examples.im.common.packets.Address getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Address>
      PARSER = new com.google.protobuf.AbstractParser<Address>() {
    public Address parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Address(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Address> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Address> getParserForType() {
    return PARSER;
  }

  public org.tio.examples.im.common.packets.Address getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

