// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package org.tio.examples.im.common.packets;

public interface ChatReqBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ChatReqBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *消息发送时间
   * </pre>
   *
   * <code>int64 time = 1;</code>
   */
  long getTime();

  /**
   * <pre>
   *聊天类型
   * </pre>
   *
   * <code>.ChatType type = 2;</code>
   */
  int getTypeValue();
  /**
   * <pre>
   *聊天类型
   * </pre>
   *
   * <code>.ChatType type = 2;</code>
   */
  org.tio.examples.im.common.packets.ChatType getType();

  /**
   * <pre>
   *聊天内容
   * </pre>
   *
   * <code>string text = 3;</code>
   */
  java.lang.String getText();
  /**
   * <pre>
   *聊天内容
   * </pre>
   *
   * <code>string text = 3;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <pre>
   *消息发到哪个群组
   * </pre>
   *
   * <code>string group = 4;</code>
   */
  java.lang.String getGroup();
  /**
   * <pre>
   *消息发到哪个群组
   * </pre>
   *
   * <code>string group = 4;</code>
   */
  com.google.protobuf.ByteString
      getGroupBytes();

  /**
   * <pre>
   *目标channel id
   * </pre>
   *
   * <code>string toId = 5;</code>
   */
  java.lang.String getToId();
  /**
   * <pre>
   *目标channel id
   * </pre>
   *
   * <code>string toId = 5;</code>
   */
  com.google.protobuf.ByteString
      getToIdBytes();
}
