// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package org.tio.examples.im.common.packets;

public interface ClientOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Client)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *ChannelContext id
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <pre>
   *ChannelContext id
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   *客户端ip
   * </pre>
   *
   * <code>string ip = 2;</code>
   */
  java.lang.String getIp();
  /**
   * <pre>
   *客户端ip
   * </pre>
   *
   * <code>string ip = 2;</code>
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <pre>
   *客户端port
   * </pre>
   *
   * <code>int32 port = 3;</code>
   */
  int getPort();

  /**
   * <pre>
   *如果没登录过，则为null
   * </pre>
   *
   * <code>.User user = 4;</code>
   */
  boolean hasUser();
  /**
   * <pre>
   *如果没登录过，则为null
   * </pre>
   *
   * <code>.User user = 4;</code>
   */
  org.tio.examples.im.common.packets.User getUser();
  /**
   * <pre>
   *如果没登录过，则为null
   * </pre>
   *
   * <code>.User user = 4;</code>
   */
  org.tio.examples.im.common.packets.UserOrBuilder getUserOrBuilder();

  /**
   * <pre>
   *ip所在地区
   * </pre>
   *
   * <code>string region = 5;</code>
   */
  java.lang.String getRegion();
  /**
   * <pre>
   *ip所在地区
   * </pre>
   *
   * <code>string region = 5;</code>
   */
  com.google.protobuf.ByteString
      getRegionBytes();

  /**
   * <pre>
   *浏览器信息
   * </pre>
   *
   * <code>string useragent = 6;</code>
   */
  java.lang.String getUseragent();
  /**
   * <pre>
   *浏览器信息
   * </pre>
   *
   * <code>string useragent = 6;</code>
   */
  com.google.protobuf.ByteString
      getUseragentBytes();

  /**
   * <pre>
   *ip所属运营商
   * </pre>
   *
   * <code>string operator = 7;</code>
   */
  java.lang.String getOperator();
  /**
   * <pre>
   *ip所属运营商
   * </pre>
   *
   * <code>string operator = 7;</code>
   */
  com.google.protobuf.ByteString
      getOperatorBytes();

  /**
   * <pre>
   *地图定位
   * </pre>
   *
   * <code>.Geolocation geolocation = 8;</code>
   */
  boolean hasGeolocation();
  /**
   * <pre>
   *地图定位
   * </pre>
   *
   * <code>.Geolocation geolocation = 8;</code>
   */
  org.tio.examples.im.common.packets.Geolocation getGeolocation();
  /**
   * <pre>
   *地图定位
   * </pre>
   *
   * <code>.Geolocation geolocation = 8;</code>
   */
  org.tio.examples.im.common.packets.GeolocationOrBuilder getGeolocationOrBuilder();

  /**
   * <pre>
   *地址
   * </pre>
   *
   * <code>.Address address = 9;</code>
   */
  boolean hasAddress();
  /**
   * <pre>
   *地址
   * </pre>
   *
   * <code>.Address address = 9;</code>
   */
  org.tio.examples.im.common.packets.Address getAddress();
  /**
   * <pre>
   *地址
   * </pre>
   *
   * <code>.Address address = 9;</code>
   */
  org.tio.examples.im.common.packets.AddressOrBuilder getAddressOrBuilder();
}
