// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package org.tio.examples.im.common.packets;

public interface GeolocationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Geolocation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *lng、lat分别代表经度、纬度值
   * </pre>
   *
   * <code>double lng = 1;</code>
   */
  double getLng();

  /**
   * <pre>
   *纬度
   * </pre>
   *
   * <code>double lat = 2;</code>
   */
  double getLat();
}
