// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package org.tio.examples.im.common.packets;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *user id
   * </pre>
   *
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <pre>
   *user nick
   * </pre>
   *
   * <code>string nick = 2;</code>
   */
  java.lang.String getNick();
  /**
   * <pre>
   *user nick
   * </pre>
   *
   * <code>string nick = 2;</code>
   */
  com.google.protobuf.ByteString
      getNickBytes();

  /**
   * <pre>
   *用户头像
   * </pre>
   *
   * <code>string avatar = 3;</code>
   */
  java.lang.String getAvatar();
  /**
   * <pre>
   *用户头像
   * </pre>
   *
   * <code>string avatar = 3;</code>
   */
  com.google.protobuf.ByteString
      getAvatarBytes();
}
