// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package org.tio.examples.im.common.packets;

/**
 * <pre>
 *退出群组通知消息体
 * </pre>
 *
 * Protobuf type {@code ExitGroupNotifyRespBody}
 */
public final class ExitGroupNotifyRespBody extends com.google.protobuf.GeneratedMessageV3 implements
		// @@protoc_insertion_point(message_implements:ExitGroupNotifyRespBody)
		ExitGroupNotifyRespBodyOrBuilder {
	/**
	 * <pre>
	 *退出群组通知消息体
	 * </pre>
	 *
	 * Protobuf type {@code ExitGroupNotifyRespBody}
	 */
	public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
			// @@protoc_insertion_point(builder_implements:ExitGroupNotifyRespBody)
			org.tio.examples.im.common.packets.ExitGroupNotifyRespBodyOrBuilder {
		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return org.tio.examples.im.common.packets.Chat.internal_static_ExitGroupNotifyRespBody_descriptor;
		}

		private org.tio.examples.im.common.packets.Client client_ = null;

		private com.google.protobuf.SingleFieldBuilderV3<org.tio.examples.im.common.packets.Client, org.tio.examples.im.common.packets.Client.Builder, org.tio.examples.im.common.packets.ClientOrBuilder> clientBuilder_;

		private java.lang.Object group_ = "";

		// Construct using org.tio.examples.im.common.packets.ExitGroupNotifyRespBody.newBuilder()
		private Builder() {
			maybeForceBuilderInitialization();
		}

		private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			super(parent);
			maybeForceBuilderInitialization();
		}

		@Override
		public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
			return super.addRepeatedField(field, value);
		}

		@Override
		public org.tio.examples.im.common.packets.ExitGroupNotifyRespBody build() {
			org.tio.examples.im.common.packets.ExitGroupNotifyRespBody result = buildPartial();
			if (!result.isInitialized()) {
				throw newUninitializedMessageException(result);
			}
			return result;
		}

		@Override
		public org.tio.examples.im.common.packets.ExitGroupNotifyRespBody buildPartial() {
			org.tio.examples.im.common.packets.ExitGroupNotifyRespBody result = new org.tio.examples.im.common.packets.ExitGroupNotifyRespBody(this);
			if (clientBuilder_ == null) {
				result.client_ = client_;
			} else {
				result.client_ = clientBuilder_.build();
			}
			result.group_ = group_;
			onBuilt();
			return result;
		}

		@Override
		public Builder clear() {
			super.clear();
			if (clientBuilder_ == null) {
				client_ = null;
			} else {
				client_ = null;
				clientBuilder_ = null;
			}
			group_ = "";

			return this;
		}

		/**
		 * <code>.Client client = 1;</code>
		 */
		public Builder clearClient() {
			if (clientBuilder_ == null) {
				client_ = null;
				onChanged();
			} else {
				client_ = null;
				clientBuilder_ = null;
			}

			return this;
		}

		@Override
		public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
			return super.clearField(field);
		}

		/**
		 * <code>string group = 2;</code>
		 */
		public Builder clearGroup() {

			group_ = getDefaultInstance().getGroup();
			onChanged();
			return this;
		}

		@Override
		public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
			return super.clearOneof(oneof);
		}

		@Override
		public Builder clone() {
			return super.clone();
		}

		/**
		 * <code>.Client client = 1;</code>
		 */
		@Override
		public org.tio.examples.im.common.packets.Client getClient() {
			if (clientBuilder_ == null) {
				return client_ == null ? org.tio.examples.im.common.packets.Client.getDefaultInstance() : client_;
			} else {
				return clientBuilder_.getMessage();
			}
		}

		/**
		 * <code>.Client client = 1;</code>
		 */
		public org.tio.examples.im.common.packets.Client.Builder getClientBuilder() {

			onChanged();
			return getClientFieldBuilder().getBuilder();
		}

		/**
		 * <code>.Client client = 1;</code>
		 */
		private com.google.protobuf.SingleFieldBuilderV3<org.tio.examples.im.common.packets.Client, org.tio.examples.im.common.packets.Client.Builder, org.tio.examples.im.common.packets.ClientOrBuilder> getClientFieldBuilder() {
			if (clientBuilder_ == null) {
				clientBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<>(
						getClient(), getParentForChildren(), isClean());
				client_ = null;
			}
			return clientBuilder_;
		}

		/**
		 * <code>.Client client = 1;</code>
		 */
		@Override
		public org.tio.examples.im.common.packets.ClientOrBuilder getClientOrBuilder() {
			if (clientBuilder_ != null) {
				return clientBuilder_.getMessageOrBuilder();
			} else {
				return client_ == null ? org.tio.examples.im.common.packets.Client.getDefaultInstance() : client_;
			}
		}

		@Override
		public org.tio.examples.im.common.packets.ExitGroupNotifyRespBody getDefaultInstanceForType() {
			return org.tio.examples.im.common.packets.ExitGroupNotifyRespBody.getDefaultInstance();
		}

		@Override
		public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
			return org.tio.examples.im.common.packets.Chat.internal_static_ExitGroupNotifyRespBody_descriptor;
		}

		/**
		 * <code>string group = 2;</code>
		 */
		@Override
		public java.lang.String getGroup() {
			java.lang.Object ref = group_;
			if (!(ref instanceof java.lang.String)) {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				group_ = s;
				return s;
			} else {
				return (java.lang.String) ref;
			}
		}

		/**
		 * <code>string group = 2;</code>
		 */
		@Override
		public com.google.protobuf.ByteString getGroupBytes() {
			java.lang.Object ref = group_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				group_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		/**
		 * <code>.Client client = 1;</code>
		 */
		@Override
		public boolean hasClient() {
			return clientBuilder_ != null || client_ != null;
		}

		@Override
		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return org.tio.examples.im.common.packets.Chat.internal_static_ExitGroupNotifyRespBody_fieldAccessorTable.ensureFieldAccessorsInitialized(
					org.tio.examples.im.common.packets.ExitGroupNotifyRespBody.class, org.tio.examples.im.common.packets.ExitGroupNotifyRespBody.Builder.class);
		}

		@Override
		public final boolean isInitialized() {
			return true;
		}

		private void maybeForceBuilderInitialization() {
			if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
			}
		}

		/**
		 * <code>.Client client = 1;</code>
		 */
		public Builder mergeClient(org.tio.examples.im.common.packets.Client value) {
			if (clientBuilder_ == null) {
				if (client_ != null) {
					client_ = org.tio.examples.im.common.packets.Client.newBuilder(client_).mergeFrom(value).buildPartial();
				} else {
					client_ = value;
				}
				onChanged();
			} else {
				clientBuilder_.mergeFrom(value);
			}

			return this;
		}

		@Override
		public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			org.tio.examples.im.common.packets.ExitGroupNotifyRespBody parsedMessage = null;
			try {
				parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				parsedMessage = (org.tio.examples.im.common.packets.ExitGroupNotifyRespBody) e.getUnfinishedMessage();
				throw e.unwrapIOException();
			} finally {
				if (parsedMessage != null) {
					mergeFrom(parsedMessage);
				}
			}
			return this;
		}

		@Override
		public Builder mergeFrom(com.google.protobuf.Message other) {
			if (other instanceof org.tio.examples.im.common.packets.ExitGroupNotifyRespBody) {
				return mergeFrom((org.tio.examples.im.common.packets.ExitGroupNotifyRespBody) other);
			} else {
				super.mergeFrom(other);
				return this;
			}
		}

		public Builder mergeFrom(org.tio.examples.im.common.packets.ExitGroupNotifyRespBody other) {
			if (other == org.tio.examples.im.common.packets.ExitGroupNotifyRespBody.getDefaultInstance()) {
				return this;
			}
			if (other.hasClient()) {
				mergeClient(other.getClient());
			}
			if (!other.getGroup().isEmpty()) {
				group_ = other.group_;
				onChanged();
			}
			onChanged();
			return this;
		}

		@Override
		public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
			return this;
		}

		/**
		 * <code>.Client client = 1;</code>
		 */
		public Builder setClient(org.tio.examples.im.common.packets.Client value) {
			if (clientBuilder_ == null) {
				if (value == null) {
					throw new NullPointerException();
				}
				client_ = value;
				onChanged();
			} else {
				clientBuilder_.setMessage(value);
			}

			return this;
		}

		/**
		 * <code>.Client client = 1;</code>
		 */
		public Builder setClient(org.tio.examples.im.common.packets.Client.Builder builderForValue) {
			if (clientBuilder_ == null) {
				client_ = builderForValue.build();
				onChanged();
			} else {
				clientBuilder_.setMessage(builderForValue.build());
			}

			return this;
		}

		@Override
		public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
			return super.setField(field, value);
		}

		/**
		 * <code>string group = 2;</code>
		 */
		public Builder setGroup(java.lang.String value) {
			if (value == null) {
				throw new NullPointerException();
			}

			group_ = value;
			onChanged();
			return this;
		}

		/**
		 * <code>string group = 2;</code>
		 */
		public Builder setGroupBytes(com.google.protobuf.ByteString value) {
			if (value == null) {
				throw new NullPointerException();
			}
			checkByteStringIsUtf8(value);

			group_ = value;
			onChanged();
			return this;
		}

		@Override
		public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index, Object value) {
			return super.setRepeatedField(field, index, value);
		}

		@Override
		public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
			return this;
		}

		// @@protoc_insertion_point(builder_scope:ExitGroupNotifyRespBody)
	}

	public static final int CLIENT_FIELD_NUMBER = 1;

	public static final int GROUP_FIELD_NUMBER = 2;

	private static final long serialVersionUID = 0L;

	// @@protoc_insertion_point(class_scope:ExitGroupNotifyRespBody)
	private static final org.tio.examples.im.common.packets.ExitGroupNotifyRespBody DEFAULT_INSTANCE;

	static {
		DEFAULT_INSTANCE = new org.tio.examples.im.common.packets.ExitGroupNotifyRespBody();
	}

	private static final com.google.protobuf.Parser<ExitGroupNotifyRespBody> PARSER = new com.google.protobuf.AbstractParser<ExitGroupNotifyRespBody>() {
		@Override
		public ExitGroupNotifyRespBody parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return new ExitGroupNotifyRespBody(input, extensionRegistry);
		}
	};

	public static org.tio.examples.im.common.packets.ExitGroupNotifyRespBody getDefaultInstance() {
		return DEFAULT_INSTANCE;
	}

	public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
		return org.tio.examples.im.common.packets.Chat.internal_static_ExitGroupNotifyRespBody_descriptor;
	}

	public static Builder newBuilder() {
		return DEFAULT_INSTANCE.toBuilder();
	}

	public static Builder newBuilder(org.tio.examples.im.common.packets.ExitGroupNotifyRespBody prototype) {
		return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
	}

	public static org.tio.examples.im.common.packets.ExitGroupNotifyRespBody parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
	}

	public static org.tio.examples.im.common.packets.ExitGroupNotifyRespBody parseDelimitedFrom(java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
	}

	public static org.tio.examples.im.common.packets.ExitGroupNotifyRespBody parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static org.tio.examples.im.common.packets.ExitGroupNotifyRespBody parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static org.tio.examples.im.common.packets.ExitGroupNotifyRespBody parseFrom(com.google.protobuf.ByteString data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static org.tio.examples.im.common.packets.ExitGroupNotifyRespBody parseFrom(com.google.protobuf.ByteString data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static org.tio.examples.im.common.packets.ExitGroupNotifyRespBody parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
	}

	public static org.tio.examples.im.common.packets.ExitGroupNotifyRespBody parseFrom(com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
	}

	public static org.tio.examples.im.common.packets.ExitGroupNotifyRespBody parseFrom(java.io.InputStream input) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
	}

	public static org.tio.examples.im.common.packets.ExitGroupNotifyRespBody parseFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
	}

	public static com.google.protobuf.Parser<ExitGroupNotifyRespBody> parser() {
		return PARSER;
	}

	private org.tio.examples.im.common.packets.Client client_;

	private volatile java.lang.Object group_;

	private byte memoizedIsInitialized = -1;

	private ExitGroupNotifyRespBody() {
		group_ = "";
	}

	private ExitGroupNotifyRespBody(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		this();
		int mutable_bitField0_ = 0;
		try {
			boolean done = false;
			while (!done) {
				int tag = input.readTag();
				switch (tag) {
				case 0:
					done = true;
					break;
				default: {
					if (!input.skipField(tag)) {
						done = true;
					}
					break;
				}
				case 10: {
					org.tio.examples.im.common.packets.Client.Builder subBuilder = null;
					if (client_ != null) {
						subBuilder = client_.toBuilder();
					}
					client_ = input.readMessage(org.tio.examples.im.common.packets.Client.parser(), extensionRegistry);
					if (subBuilder != null) {
						subBuilder.mergeFrom(client_);
						client_ = subBuilder.buildPartial();
					}

					break;
				}
				case 18: {
					java.lang.String s = input.readStringRequireUtf8();

					group_ = s;
					break;
				}
				}
			}
		} catch (com.google.protobuf.InvalidProtocolBufferException e) {
			throw e.setUnfinishedMessage(this);
		} catch (java.io.IOException e) {
			throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
		} finally {
			makeExtensionsImmutable();
		}
	}

	// Use ExitGroupNotifyRespBody.newBuilder() to construct.
	private ExitGroupNotifyRespBody(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
		super(builder);
	}

	@java.lang.Override
	public boolean equals(final java.lang.Object obj) {
		if (obj == this) {
			return true;
		}
		if (!(obj instanceof org.tio.examples.im.common.packets.ExitGroupNotifyRespBody)) {
			return super.equals(obj);
		}
		org.tio.examples.im.common.packets.ExitGroupNotifyRespBody other = (org.tio.examples.im.common.packets.ExitGroupNotifyRespBody) obj;

		boolean result = true;
		result = result && hasClient() == other.hasClient();
		if (hasClient()) {
			result = result && getClient().equals(other.getClient());
		}
		result = result && getGroup().equals(other.getGroup());
		return result;
	}

	/**
	 * <code>.Client client = 1;</code>
	 */
	@Override
	public org.tio.examples.im.common.packets.Client getClient() {
		return client_ == null ? org.tio.examples.im.common.packets.Client.getDefaultInstance() : client_;
	}

	/**
	 * <code>.Client client = 1;</code>
	 */
	@Override
	public org.tio.examples.im.common.packets.ClientOrBuilder getClientOrBuilder() {
		return getClient();
	}

	@Override
	public org.tio.examples.im.common.packets.ExitGroupNotifyRespBody getDefaultInstanceForType() {
		return DEFAULT_INSTANCE;
	}

	/**
	 * <code>string group = 2;</code>
	 */
	@Override
	public java.lang.String getGroup() {
		java.lang.Object ref = group_;
		if (ref instanceof java.lang.String) {
			return (java.lang.String) ref;
		} else {
			com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
			java.lang.String s = bs.toStringUtf8();
			group_ = s;
			return s;
		}
	}

	/**
	 * <code>string group = 2;</code>
	 */
	@Override
	public com.google.protobuf.ByteString getGroupBytes() {
		java.lang.Object ref = group_;
		if (ref instanceof java.lang.String) {
			com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
			group_ = b;
			return b;
		} else {
			return (com.google.protobuf.ByteString) ref;
		}
	}

	@java.lang.Override
	public com.google.protobuf.Parser<ExitGroupNotifyRespBody> getParserForType() {
		return PARSER;
	}

	@Override
	public int getSerializedSize() {
		int size = memoizedSize;
		if (size != -1) {
			return size;
		}

		size = 0;
		if (client_ != null) {
			size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, getClient());
		}
		if (!getGroupBytes().isEmpty()) {
			size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, group_);
		}
		memoizedSize = size;
		return size;
	}

	@java.lang.Override
	public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
		return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
	}

	/**
	 * <code>.Client client = 1;</code>
	 */
	@Override
	public boolean hasClient() {
		return client_ != null;
	}

	@java.lang.Override
	public int hashCode() {
		if (memoizedHashCode != 0) {
			return memoizedHashCode;
		}
		int hash = 41;
		hash = 19 * hash + getDescriptor().hashCode();
		if (hasClient()) {
			hash = 37 * hash + CLIENT_FIELD_NUMBER;
			hash = 53 * hash + getClient().hashCode();
		}
		hash = 37 * hash + GROUP_FIELD_NUMBER;
		hash = 53 * hash + getGroup().hashCode();
		hash = 29 * hash + unknownFields.hashCode();
		memoizedHashCode = hash;
		return hash;
	}

	@Override
	protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
		return org.tio.examples.im.common.packets.Chat.internal_static_ExitGroupNotifyRespBody_fieldAccessorTable.ensureFieldAccessorsInitialized(
				org.tio.examples.im.common.packets.ExitGroupNotifyRespBody.class, org.tio.examples.im.common.packets.ExitGroupNotifyRespBody.Builder.class);
	}

	@Override
	public final boolean isInitialized() {
		byte isInitialized = memoizedIsInitialized;
		if (isInitialized == 1) {
			return true;
		}
		if (isInitialized == 0) {
			return false;
		}

		memoizedIsInitialized = 1;
		return true;
	}

	@Override
	public Builder newBuilderForType() {
		return newBuilder();
	}

	@java.lang.Override
	protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
		Builder builder = new Builder(parent);
		return builder;
	}

	@Override
	public Builder toBuilder() {
		return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
	}

	@Override
	public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
		if (client_ != null) {
			output.writeMessage(1, getClient());
		}
		if (!getGroupBytes().isEmpty()) {
			com.google.protobuf.GeneratedMessageV3.writeString(output, 2, group_);
		}
	}

}
