// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package org.tio.examples.im.common.packets;

public interface LoginReqBodyOrBuilder extends
		// @@protoc_insertion_point(interface_extends:LoginReqBody)
		com.google.protobuf.MessageOrBuilder {

	/**
	 * <code>string loginname = 1;</code>
	 */
	java.lang.String getLoginname();

	/**
	 * <code>string loginname = 1;</code>
	 */
	com.google.protobuf.ByteString getLoginnameBytes();

	/**
	 * <code>string password = 2;</code>
	 */
	java.lang.String getPassword();

	/**
	 * <code>string password = 2;</code>
	 */
	com.google.protobuf.ByteString getPasswordBytes();

	/**
	 * <code>string token = 3;</code>
	 */
	java.lang.String getToken();

	/**
	 * <code>string token = 3;</code>
	 */
	com.google.protobuf.ByteString getTokenBytes();
}
